version: '3.4'

services:
  codecheftrackuser:
    image: codecheftrackuser
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      GO_ENV: development
    env_file:
      - .env
    volumes:
      - .:/app
    command: air
